spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: select 1
      url: jdbc:mysql://localhoat:3306/icourse?serverTimezone=Asia/Shanghai
      username: icourse
      password: icourse@123
