server:
  port: 8180

spring:
  application:
    name: icourse-admin
  profiles:
    active: dev

feign:
  okhttp:
    enabled: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl